# Usa Node.js 20 (requerido por file-type@21+) y Yarn como gestor de paquetes
[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

# Instala dependencias usando el lockfile para asegurar consistencia
[phases.install]
cmds = ["yarn install --frozen-lockfile"]

# Compila el proyecto NestJS
[phases.build]
cmds = ["yarn build"]

# Inicia la aplicación usando el archivo generado en dist/
[start]
cmd = "yarn start"
